package com.heikinashi.monitoring.infrastructure;

import jakarta.inject.Singleton;
import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;

/**
 * Build identity of the running artifact, read once at startup from the
 * {@code git.properties} resource generated by git-commit-id-maven-plugin.
 *
 * <p>The handlers log {@link #label()} on every invocation so that "which
 * build produced this run?" — the recurring deploy-provenance question — is
 * answerable from CloudWatch alone, without comparing artifact hashes.
 */
@Singleton
public class BuildInfo {

    private static final String UNKNOWN = "unknown";

    private final String label;

    public BuildInfo() {
        this(loadGitProperties());
    }

    BuildInfo(Properties p) {
        this.label = p.getProperty("git.build.version", UNKNOWN)
                + "+" + p.getProperty("git.commit.id.abbrev", UNKNOWN)
                + " branch=" + p.getProperty("git.branch", UNKNOWN)
                + " built=" + p.getProperty("git.build.time", UNKNOWN);
    }

    /** e.g. {@code 0.42.0-alpha+1a2b3c4 branch=main built=2026-05-18T23:00:00Z}. */
    public String label() {
        return label;
    }

    private static Properties loadGitProperties() {
        Properties p = new Properties();
        try (InputStream in = BuildInfo.class.getResourceAsStream("/git.properties")) {
            if (in != null) {
                p.load(in);
            }
        } catch (IOException e) {
            // git.properties unreadable — build info simply stays "unknown".
        }
        return p;
    }
}
